import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

// Import Urbanist from Google Fonts
const urbanist = Urbanist({
  subsets: ["latin"],
weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-slate-900 text-slate-100">
     
      <body className={`${urbanist.className} antialiased`}>
      <Header />
        {children}
        <div className="h-[500vh]"></div>
        </body>
    </html>
  );
}
